# Generated by Django 4.0.2 on 2022-03-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_ipmanager_ipmanagerdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipmanagerdb',
            name='site_view',
            field=models.IntegerField(default=0),
        ),
    ]
