# Generated by Django 4.0.2 on 2022-03-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_ipmanagerdb_site_view_ipmanagerdb_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipmanagerdb',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
