# Generated by Django 4.0.2 on 2022-03-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ipmanagerdb_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipmanagerdb',
            name='ip',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
