# Generated by Django 4.0.2 on 2022-03-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_ipmanagerdb_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipmanagerdb',
            name='access',
            field=models.BooleanField(default=True, verbose_name='Access'),
        ),
        migrations.AlterField(
            model_name='ipmanagerdb',
            name='ip',
            field=models.CharField(max_length=16, unique=True, verbose_name='Ip'),
        ),
        migrations.AlterField(
            model_name='ipmanagerdb',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
    ]
