# Generated by Django 4.0.2 on 2022-04-03 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ipmanagerdb_city_ipmanagerdb_country_ipmanagerdb_lat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipmanagerdb',
            options={'verbose_name': 'IpManagerDb', 'verbose_name_plural': 'IpsManagerDb'},
        ),
    ]
