# Generated by Django 4.0.2 on 2022-02-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'ContactUs', 'verbose_name_plural': 'ContactUs'},
        ),
    ]
