# Generated by Django 4.0.2 on 2022-02-16 18:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('delete_timestamp', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='This is deleted datetime', null=True, verbose_name='Deleted Datetime')),
                ('is_deleted', models.BooleanField(default=False, help_text='This is deleted status', verbose_name='Deleted status')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=64, verbose_name='Password')),
                ('f_name', models.CharField(max_length=64, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=64, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Phone Number Is Not Valid', regex='^(9|(09))(((1)|(3))([0-9])|(20)|(21))(\\d{7})')], verbose_name='Phone')),
                ('email', models.EmailField(max_length=64, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Costumer',
                'verbose_name_plural': 'Costumers',
            },
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('delete_timestamp', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='This is deleted datetime', null=True, verbose_name='Deleted Datetime')),
                ('is_deleted', models.BooleanField(default=False, help_text='This is deleted status', verbose_name='Deleted status')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('state', models.CharField(max_length=64, verbose_name='State')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('postal_code', models.IntegerField(unique=True, verbose_name='PostalCode')),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customers.costumers', verbose_name='Costumer')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
