# Generated by Django 4.0.2 on 2022-02-16 15:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='costumers',
            options={'verbose_name': 'Costumer', 'verbose_name_plural': 'Costumers'},
        ),
        migrations.AlterField(
            model_name='addresses',
            name='city',
            field=models.CharField(max_length=64, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customers.costumers', verbose_name='Costumer'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='postal_code',
            field=models.IntegerField(unique=True, verbose_name='PostalCode'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='state',
            field=models.CharField(max_length=64, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='costumers',
            name='email',
            field=models.EmailField(max_length=64, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='costumers',
            name='f_name',
            field=models.CharField(max_length=64, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='costumers',
            name='l_name',
            field=models.CharField(max_length=64, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='costumers',
            name='password',
            field=models.CharField(max_length=64, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='costumers',
            name='phone',
            field=models.CharField(max_length=16, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='costumers',
            name='username',
            field=models.CharField(max_length=64, unique=True, verbose_name='Username'),
        ),
    ]
