# Generated by Django 4.0.2 on 2022-02-13 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('delete_timestamp', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='This is deleted datetime', null=True, verbose_name='Deleted Datetime')),
                ('is_deleted', models.BooleanField(default=False, help_text='This is deleted status', verbose_name='Deleted status')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('item_count', models.IntegerField()),
                ('status', models.CharField(choices=[('waiting', 'wait for accept admin'), ('sending', 'sending to costumer'), ('received', 'received to costumer')], max_length=32)),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='customers.costumers')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.products')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
