# Generated by Django 4.0.2 on 2022-02-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='customers.addresses', verbose_name='Address'),
            preserve_default=False,
        ),
    ]
