# Generated by Django 4.0.2 on 2022-03-20 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_costumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cancel'), (1, 'Unpaid'), (2, 'Paid'), (3, 'Waiting')], default=1, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('delete_timestamp', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='This is deleted datetime', null=True, verbose_name='Deleted Datetime')),
                ('is_deleted', models.BooleanField(default=False, help_text='This is deleted status', verbose_name='Deleted status')),
                ('is_active', models.BooleanField(default=True, help_text='This is active status', verbose_name='Active status')),
                ('transactionId', models.CharField(max_length=256, verbose_name='TransactionId')),
                ('transactionLink', models.CharField(max_length=500, verbose_name='TransactionLink')),
                ('status', models.IntegerField(choices=[(0, 'Cancel'), (1, 'Unpaid'), (2, 'Paid'), (3, 'Waiting')], default=1, verbose_name='Status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders.order', verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
