# Generated by Django 4.0.2 on 2022-03-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cancel'), (1, 'Unpaid'), (2, 'Paid'), (3, 'Waiting')], default=3, verbose_name='Status'),
        ),
    ]
