# Generated by Django 4.0.2 on 2022-02-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='products.Categories', verbose_name='Category'),
        ),
    ]
