# Generated by Django 4.0.2 on 2022-02-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, help_text='Best format is .png or .jpg', null=True, upload_to='uploads/', verbose_name='Image'),
        ),
    ]
