# Generated by Django 4.0.2 on 2022-02-13 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_categories_options_categories_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='categories',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='categories',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='slug',
        ),
    ]
