# Generated by Django 4.0.2 on 2022-02-17 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(99)], verbose_name='Value'),
        ),
    ]
