# Generated by Django 4.0.2 on 2022-02-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_discount_max_price_alter_discount_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='code',
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
