# Generated by Django 4.0.2 on 2022-02-17 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_discount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(2)], verbose_name='Value'),
        ),
    ]
