# Generated by Django 4.0.2 on 2022-02-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_discount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Value'),
        ),
    ]
