# Generated by Django 4.0.2 on 2022-02-16 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Discount', 'verbose_name_plural': 'Discounts'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='products.discount', verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.categories', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='type',
            field=models.CharField(max_length=64, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='max_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max_Price'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('price', 'Price'), ('percent', 'Percent')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(to='products.Categories', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='products.discount', verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
    ]
