# Generated by Django 4.0.2 on 2022-02-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_discount_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='discount',
        ),
    ]
